// src/constants/icons.ts
import {
  Home,
  Search,
  PlusSquare,
  Bookmark,
  Compass,
  LayoutGrid,
  Heart,
  HeartCrack,
  User,
  Menu,
  Send,
  Facebook,
  Instagram,
  Circle,
  MessageCircle,
  UserRound,
  BadgeCheck,
  ArrowLeft,
  MoreHorizontal,
  Image,
  Clapperboard,
} from "lucide-react";

export const ICONS = {
  home: Home,
  explore: Compass,
  search: Search,
  addPost: PlusSquare,
  profile: User,
  menu: Menu,
  grid: LayoutGrid,
  bookmark: Bookmark,
  likeOutline: Heart,
  likeFilled: HeartCrack,
  comment: MessageCircle,
  share: Send,
  userSquare: UserRound,
  instagram: Instagram,
  facebook: Facebook,
  verified: BadgeCheck,
  back: ArrowLeft,
  more: MoreHorizontal,
  media: Image,
  circle: Circle,
  clapperboard: Clapperboard,
};
